<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="4" ignored="3" total="11" passed="4">
  <reporter-output>
    <line>
      <![CDATA[ReportTest Class Started..]]>
    </line>
    <line>
      <![CDATA[ReportTesttest Started..]]>
    </line>
    <line>
      <![CDATA[Login Test Started..]]>
    </line>
    <line>
      <![CDATA[Login Test Passed..]]>
    </line>
    <line>
      <![CDATA[Login1 Test Started..]]>
    </line>
    <line>
      <![CDATA[Login1 Test Failed..java.lang.AssertionError: expected [true] but found [false]]]>
    </line>
    <line>
      <![CDATA[Login2 Test Started..]]>
    </line>
    <line>
      <![CDATA[Login2 Test Passed..]]>
    </line>
    <line>
      <![CDATA[Login3 Test Started..]]>
    </line>
    <line>
      <![CDATA[Login3 Test Failed..java.lang.AssertionError: expected [true] but found [false]]]>
    </line>
    <line>
      <![CDATA[testLogin4 Test Started..]]>
    </line>
    <line>
      <![CDATA[testLogin4 Test Failed..java.lang.AssertionError: expected [true] but found [false]]]>
    </line>
    <line>
      <![CDATA[testLogin5 Test Started..]]>
    </line>
    <line>
      <![CDATA[testLogin5 Test Passed..]]>
    </line>
    <line>
      <![CDATA[testLogin6 Test Started..]]>
    </line>
    <line>
      <![CDATA[testLogin6 Test Failed..java.lang.AssertionError: expected [true] but found [false]]]>
    </line>
    <line>
      <![CDATA[TestscreenTest Test Started..]]>
    </line>
    <line>
      <![CDATA[<a href='G:\Javaprogramming\uiframework\src\main\resources\screenshots\second_30_54_2019_10_54_58.png'><img src='G:\Javaprogramming\uiframework\src\main\resources\screenshots\second_30_54_2019_10_54_58.png'height='100' width='100'/></a>]]>
    </line>
    <line>
      <![CDATA[TestscreenTest Test Passed..]]>
    </line>
  </reporter-output>
  <suite name="Smoke suite" duration-ms="25476" started-at="2019-01-30T17:24:33Z" finished-at="2019-01-30T17:24:58Z">
    <groups>
    </groups>
    <test name="ReportTest" duration-ms="25476" started-at="2019-01-30T17:24:33Z" finished-at="2019-01-30T17:24:58Z">
      <class name="uiframework.uiframework.Paragcom.freecrm.TestScript.TestScreen">
        <test-method status="PASS" signature="beforeMethod(java.lang.reflect.Method)[pri:0, instance:uiframework.uiframework.Paragcom.freecrm.TestScript.TestScreen@67784306]" name="beforeMethod" is-config="true" duration-ms="0" started-at="2019-01-30T17:24:51Z" finished-at="2019-01-30T17:24:51Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void uiframework.uiframework.Paragcom.freecrm.TestScript.TestScreen.TestscreenTest() throws java.lang.Exception]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="PASS" signature="TestscreenTest()[pri:0, instance:uiframework.uiframework.Paragcom.freecrm.TestScript.TestScreen@67784306]" name="TestscreenTest" duration-ms="6985" started-at="2019-01-30T17:24:51Z" finished-at="2019-01-30T17:24:58Z">
          <reporter-output>
            <line>
              <![CDATA[TestscreenTest Test Started..]]>
            </line>
            <line>
              <![CDATA[<a href='G:\Javaprogramming\uiframework\src\main\resources\screenshots\second_30_54_2019_10_54_58.png'><img src='G:\Javaprogramming\uiframework\src\main\resources\screenshots\second_30_54_2019_10_54_58.png'height='100' width='100'/></a>]]>
            </line>
            <line>
              <![CDATA[TestscreenTest Test Passed..]]>
            </line>
          </reporter-output>
        </test-method> <!-- TestscreenTest -->
        <test-method status="PASS" signature="AfterMethod(org.testng.ITestResult)[pri:0, instance:uiframework.uiframework.Paragcom.freecrm.TestScript.TestScreen@67784306]" name="AfterMethod" is-config="true" duration-ms="41" started-at="2019-01-30T17:24:58Z" finished-at="2019-01-30T17:24:58Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=TestscreenTest status=SUCCESS method=TestScreen.TestscreenTest()[pri:0, instance:uiframework.uiframework.Paragcom.freecrm.TestScript.TestScreen@67784306] output=TestscreenTest Test Started..]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AfterMethod -->
      </class> <!-- uiframework.uiframework.Paragcom.freecrm.TestScript.TestScreen -->
      <class name="uiframework.uiframework.Paragcom.freecrm.TestScript.Test2">
        <test-method status="PASS" signature="Beforesuite()[pri:0, instance:uiframework.uiframework.Paragcom.freecrm.TestScript.Test2@6f1fba17]" name="Beforesuite" is-config="true" duration-ms="163" started-at="2019-01-30T17:24:32Z" finished-at="2019-01-30T17:24:33Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Beforesuite -->
        <test-method status="PASS" signature="BeforeAnyClass()[pri:0, instance:uiframework.uiframework.Paragcom.freecrm.TestScript.Test2@6f1fba17]" name="BeforeAnyClass" is-config="true" duration-ms="4" started-at="2019-01-30T17:24:33Z" finished-at="2019-01-30T17:24:33Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- BeforeAnyClass -->
        <test-method status="PASS" signature="Beforetest()[pri:0, instance:uiframework.uiframework.Paragcom.freecrm.TestScript.Test2@6f1fba17]" name="Beforetest" is-config="true" duration-ms="17892" started-at="2019-01-30T17:24:33Z" finished-at="2019-01-30T17:24:50Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Beforetest -->
        <test-method status="PASS" signature="beforeMethod(java.lang.reflect.Method)[pri:0, instance:uiframework.uiframework.Paragcom.freecrm.TestScript.Test2@6f1fba17]" name="beforeMethod" is-config="true" duration-ms="15" started-at="2019-01-30T17:24:50Z" finished-at="2019-01-30T17:24:50Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void uiframework.uiframework.Paragcom.freecrm.TestScript.Test2.testLogin4()]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="FAIL" signature="testLogin4()[pri:0, instance:uiframework.uiframework.Paragcom.freecrm.TestScript.Test2@6f1fba17]" name="testLogin4" duration-ms="3" started-at="2019-01-30T17:24:50Z" finished-at="2019-01-30T17:24:50Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at org.testng.Assert.assertTrue(Assert.java:54)
at uiframework.uiframework.Paragcom.freecrm.helper.Aseertion.AssertHelper.markFail(AssertHelper.java:27)
at uiframework.uiframework.Paragcom.freecrm.TestScript.Test2.testLogin4(Test2.java:28)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[testLogin4 Test Started..]]>
            </line>
            <line>
              <![CDATA[testLogin4 Test Failed..java.lang.AssertionError: expected [true] but found [false]]]>
            </line>
          </reporter-output>
        </test-method> <!-- testLogin4 -->
        <test-method status="PASS" signature="AfterMethod(org.testng.ITestResult)[pri:0, instance:uiframework.uiframework.Paragcom.freecrm.TestScript.Test2@6f1fba17]" name="AfterMethod" is-config="true" duration-ms="313" started-at="2019-01-30T17:24:50Z" finished-at="2019-01-30T17:24:51Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=testLogin4 status=FAILURE method=Test2.testLogin4()[pri:0, instance:uiframework.uiframework.Paragcom.freecrm.TestScript.Test2@6f1fba17] output=testLogin4 Test Started..]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AfterMethod -->
        <test-method status="PASS" signature="beforeMethod(java.lang.reflect.Method)[pri:0, instance:uiframework.uiframework.Paragcom.freecrm.TestScript.Test2@6f1fba17]" name="beforeMethod" is-config="true" duration-ms="1" started-at="2019-01-30T17:24:51Z" finished-at="2019-01-30T17:24:51Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void uiframework.uiframework.Paragcom.freecrm.TestScript.Test2.testLogin5()]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="PASS" signature="testLogin5()[pri:0, instance:uiframework.uiframework.Paragcom.freecrm.TestScript.Test2@6f1fba17]" name="testLogin5" duration-ms="2" started-at="2019-01-30T17:24:51Z" finished-at="2019-01-30T17:24:51Z">
          <reporter-output>
            <line>
              <![CDATA[testLogin5 Test Started..]]>
            </line>
            <line>
              <![CDATA[testLogin5 Test Passed..]]>
            </line>
          </reporter-output>
        </test-method> <!-- testLogin5 -->
        <test-method status="PASS" signature="AfterMethod(org.testng.ITestResult)[pri:0, instance:uiframework.uiframework.Paragcom.freecrm.TestScript.Test2@6f1fba17]" name="AfterMethod" is-config="true" duration-ms="61" started-at="2019-01-30T17:24:51Z" finished-at="2019-01-30T17:24:51Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=testLogin5 status=SUCCESS method=Test2.testLogin5()[pri:0, instance:uiframework.uiframework.Paragcom.freecrm.TestScript.Test2@6f1fba17] output=testLogin5 Test Started..]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AfterMethod -->
        <test-method status="PASS" signature="beforeMethod(java.lang.reflect.Method)[pri:0, instance:uiframework.uiframework.Paragcom.freecrm.TestScript.Test2@6f1fba17]" name="beforeMethod" is-config="true" duration-ms="1" started-at="2019-01-30T17:24:51Z" finished-at="2019-01-30T17:24:51Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void uiframework.uiframework.Paragcom.freecrm.TestScript.Test2.testLogin6()]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="FAIL" signature="testLogin6()[pri:0, instance:uiframework.uiframework.Paragcom.freecrm.TestScript.Test2@6f1fba17]" name="testLogin6" duration-ms="2" started-at="2019-01-30T17:24:51Z" finished-at="2019-01-30T17:24:51Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at org.testng.Assert.assertTrue(Assert.java:54)
at uiframework.uiframework.Paragcom.freecrm.helper.Aseertion.AssertHelper.markFail(AssertHelper.java:27)
at uiframework.uiframework.Paragcom.freecrm.TestScript.Test2.testLogin6(Test2.java:40)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[testLogin6 Test Started..]]>
            </line>
            <line>
              <![CDATA[testLogin6 Test Failed..java.lang.AssertionError: expected [true] but found [false]]]>
            </line>
          </reporter-output>
        </test-method> <!-- testLogin6 -->
        <test-method status="PASS" signature="AfterMethod(org.testng.ITestResult)[pri:0, instance:uiframework.uiframework.Paragcom.freecrm.TestScript.Test2@6f1fba17]" name="AfterMethod" is-config="true" duration-ms="83" started-at="2019-01-30T17:24:51Z" finished-at="2019-01-30T17:24:51Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=testLogin6 status=FAILURE method=Test2.testLogin6()[pri:0, instance:uiframework.uiframework.Paragcom.freecrm.TestScript.Test2@6f1fba17] output=testLogin6 Test Started..]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AfterMethod -->
      </class> <!-- uiframework.uiframework.Paragcom.freecrm.TestScript.Test2 -->
      <class name="uiframework.uiframework.Paragcom.freecrm.TestScript.Report">
        <test-method status="PASS" signature="Login()[pri:0, instance:uiframework.uiframework.Paragcom.freecrm.TestScript.Report@185d8b6]" name="Login" duration-ms="11" started-at="2019-01-30T17:24:50Z" finished-at="2019-01-30T17:24:50Z">
          <reporter-output>
            <line>
              <![CDATA[Login Test Started..]]>
            </line>
            <line>
              <![CDATA[Login Test Passed..]]>
            </line>
          </reporter-output>
        </test-method> <!-- Login -->
        <test-method status="FAIL" signature="Login1()[pri:0, instance:uiframework.uiframework.Paragcom.freecrm.TestScript.Report@185d8b6]" name="Login1" duration-ms="3" started-at="2019-01-30T17:24:50Z" finished-at="2019-01-30T17:24:50Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at org.testng.Assert.assertTrue(Assert.java:54)
at uiframework.uiframework.Paragcom.freecrm.helper.Aseertion.AssertHelper.markFail(AssertHelper.java:27)
at uiframework.uiframework.Paragcom.freecrm.TestScript.Report.Login1(Report.java:22)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[Login1 Test Started..]]>
            </line>
            <line>
              <![CDATA[Login1 Test Failed..java.lang.AssertionError: expected [true] but found [false]]]>
            </line>
          </reporter-output>
        </test-method> <!-- Login1 -->
        <test-method status="PASS" signature="Login2()[pri:0, instance:uiframework.uiframework.Paragcom.freecrm.TestScript.Report@185d8b6]" name="Login2" duration-ms="2" started-at="2019-01-30T17:24:50Z" finished-at="2019-01-30T17:24:50Z">
          <reporter-output>
            <line>
              <![CDATA[Login2 Test Started..]]>
            </line>
            <line>
              <![CDATA[Login2 Test Passed..]]>
            </line>
          </reporter-output>
        </test-method> <!-- Login2 -->
        <test-method status="FAIL" signature="Login3()[pri:0, instance:uiframework.uiframework.Paragcom.freecrm.TestScript.Report@185d8b6]" name="Login3" duration-ms="4" started-at="2019-01-30T17:24:50Z" finished-at="2019-01-30T17:24:50Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at org.testng.Assert.assertTrue(Assert.java:54)
at uiframework.uiframework.Paragcom.freecrm.helper.Aseertion.AssertHelper.markFail(AssertHelper.java:27)
at uiframework.uiframework.Paragcom.freecrm.TestScript.Report.Login3(Report.java:34)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[Login3 Test Started..]]>
            </line>
            <line>
              <![CDATA[Login3 Test Failed..java.lang.AssertionError: expected [true] but found [false]]]>
            </line>
          </reporter-output>
        </test-method> <!-- Login3 -->
      </class> <!-- uiframework.uiframework.Paragcom.freecrm.TestScript.Report -->
    </test> <!-- ReportTest -->
  </suite> <!-- Smoke suite -->
</testng-results>
